pyproject: include sub-packages in pip package
The include pattern "libkirk" only match the top-level package so
sub-packages like libkirk.channels is missing from the pip package.
Add "libkirk.*" to also include sub-packages.

Without this kirk fails with:
  ValueError: Discover folder doesn't exist

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>